-- FindBack: PostgreSQL custom types
CREATE TYPE report_type AS ENUM ('LOST', 'FOUND');
CREATE TYPE report_status AS ENUM ('ACTIVE', 'CLAIMED', 'RESOLVED', 'CLOSED');
CREATE TYPE item_category AS ENUM (
  'ELECTRONICS','DOCUMENTS_KEYS','BAGS_LUGGAGE','CLOTHING_ACCESSORIES',
  'PETS','JEWELRY','SPORTS_EQUIPMENT','BOOKS_STATIONERY',
  'TOYS','VEHICLES','MONEY_CARDS','OTHER'
);
CREATE TYPE claim_status AS ENUM ('PENDING','APPROVED','REJECTED','WITHDRAWN','DISPUTED');
CREATE TYPE contact_pref AS ENUM ('IN_APP','EMAIL','PHONE');
CREATE TYPE match_status AS ENUM ('PENDING','DISMISSED');
CREATE TYPE notification_type AS ENUM (
  'NEW_CLAIM','CLAIM_APPROVED','CLAIM_REJECTED',
  'MATCH_FOUND','DISPUTE_RESOLVED','MODERATOR_ACTION'
);
